

const C=require('crypto'),F=require('fs')
const SY='MNTUSDT',BTC='BTCUSDT',NTFY='https://ntfy.sh/mnt-bamako-johnson-2025'
let K = { apiKey: process.env.BYBIT_API_KEY, apiSecret: process.env.BYBIT_API_SECRET }
let s={consec:0,lastLossTime:0,dPnL:0,pos:null,topPrice:0,beDone:false}
let consec=s.consec||0,last=s.lastLossTime||0,dPnL=s.dPnL||0,pos=s.pos||null,entry=s.pos?s.pos.entry:0,qty=s.pos?s.pos.qty:0,top=s.topPrice||0,be=s.beDone||false
const save=()=>F.writeFileSync('./bot-state.json',JSON.stringify({consec,lastLossTime:last,dPnL,pos:pos?{entry,qty}:null,topPrice:top,beDone:be}))
const sig=t=>C.createHmac('sha256',K.apiSecret).update(t).digest('hex')
async function bal(){try{let ts=Date.now()+'',q='accountType=UNIFIED',h=sig(ts+K.apiKey+'5000'+q),r=await fetch('https://api.bybit.com/v5/account/wallet-balance?'+q,{headers:{'X-BAPI-API-KEY':K.apiKey,'X-BAPI-TIMESTAMP':ts,'X-BAPI-RECV-WINDOW':'5000','X-BAPI-SIGN':h}}),j=await r.json(),cs=j.result.list[0].coin;let u=cs.find(c=>c.coin=='USDT'),m=cs.find(c=>c.coin=='MNT');return{usdt:parseFloat(u.walletBalance),mnt:parseFloat(m.walletBalance)}}catch(e){return{usdt:0,mnt:0}}}
async function order(side,q){let ts=Date.now()+'',b=JSON.stringify({category:'spot',symbol:SY,side,orderType:'Market',qty:String(q)}),h=sig(ts+K.apiKey+'5000'+b),r=await fetch('https://api.bybit.com/v5/order/create',{method:'POST',headers:{'X-BAPI-API-KEY':K.apiKey,'X-BAPI-TIMESTAMP':ts,'X-BAPI-RECV-WINDOW':'5000','X-BAPI-SIGN':h,'Content-Type':'application/json'},body:b}),j=await r.json();console.log(side,JSON.stringify(j).slice(0,120));return j.retCode==0||j.result?.retCode==0}
async function closes(sym){let r=await fetch(`https://api.bybit.com/v5/market/kline?category=spot&symbol=${sym}&interval=5&limit=50`),j=await r.json();return j.result.list.reverse().map(k=>parseFloat(k[4]))}
function rsi(c){let g=0,l=0;for(let i=1;i<15;i++){let d=c[i]-c[i-1];if(d>0)g+=d;else l-=d}return 100-100/(1+g/(l||1))}
async function tick(){try{let mc=await closes(SY),bc=await closes(BTC),pr=mc[mc.length-1],mr=rsi(mc.slice(-15)),br=rsi(bc.slice(-15)),bp=bc[bc.length-1],bpr=bc[bc.length-2],bd=(bp-bpr)/bpr*100,pp=(mc[mc.length-1]-mc[mc.length-2])/mc[mc.length-2]*100,b=await bal();if(!pos&&b.mnt>1){pos=1;entry=pr;qty=b.mnt;top=pr;console.log('RECOVER',qty)}if(!pos){if(Date.now()-last< (consec==1?30*60*1000:consec==2?60*60*1000:2*60*60*1000*Math.pow(2,consec-3)) && consec>=1){console.log('COOLDOWN x'+consec);return}if(mr>65){console.log('SKIP1 RSI '+mr.toFixed(1));return}if(mr>40){console.log('SKIP1b need <40 RSI '+mr.toFixed(1));return}if(br<30||br>70){console.log('SKIP2 BTC RSI '+br.toFixed(1));return}if(bd<-1.2){console.log('SKIP BTC CRASH '+bd.toFixed(2));return}if(Math.abs(pp)>2.5){console.log('SKIP PUMP '+pp.toFixed(2));return}if(dPnL<-2){console.log('SKIP DAILY');return}if(b.usdt<5){console.log('SKIP BAL '+b.usdt.toFixed(1));return}let q=Math.floor(20/pr*10)/10;if(q<0.1)q=0.1;console.log('BUY DIP '+pr+' RSI '+mr.toFixed(1)+' QTY '+q);if(await order('Buy',q)){entry=pr;qty=q;top=pr;pos=1;be=false;save();fetch(NTFY,{method:'POST',body:'BUY '+pr+' QTY '+q,headers:{Title:'BUY'}})}}else{if(pr>top)top=pr;let pnl=(pr-entry)/entry*100,ft=(pr-top)/top*100;console.log(`POS ${pnl.toFixed(2)}% TOP ${top} ft ${ft.toFixed(2)}% BE:${be} D:${dPnL.toFixed(2)}%`);if(!be&&pnl>=0.5){be=true;save();console.log('BE LOCK');fetch(NTFY,{method:'POST',body:'BE '+pnl.toFixed(2),headers:{Title:'BE'}})}if(be&&ft<=-0.5){console.log('TP '+pnl.toFixed(2));if(await order('Sell',qty)){dPnL+=pnl;pos=null;consec=0;save();fetch(NTFY,{method:'POST',body:'TP '+pnl.toFixed(2),headers:{Title:'TP'}})}}if(pnl<=-0.5){let fp=be?0.25:pnl;console.log('SL '+fp.toFixed(2));if(await order('Sell',qty)){dPnL+=fp;consec++;last=Date.now();pos=null;be=false;save();fetch(NTFY,{method:'POST',body:'SL '+fp.toFixed(2),headers:{Title:'SL'}})}}}}catch(e){console.log('ERR',e.message)}}setInterval(tick,6000);tick();console.log('LIVE DIP <40 FIXED LOADED')